development:
  amadeus_client_id:
  amadeus_client_secret:
  nytimes_api_key:
  DB_FILENAME:
  SESSION_SECRET:
  API_HOST:
  APP_HOST:
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

test:
  amadeus_client_id: 
  amadeus_client_secret: 
  nytimes_api_key: 
  DB_FILENAME: 
  SESSION_SECRET:
  API_HOST:
  APP_HOST:
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

production:
  amadeus_client_id: 
  amadeus_client_secret: 
  nytimes_api_key: 
  DB_FILENAME: 
  SESSION_SECRET:
  API_HOST:
  APP_HOST:
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>